{% set name = "ntlm-auth" %}
{% set version = "1.2.0" %}
{% set sha256 = "7bc02a3fbdfee7275d3dc20fce8028ed8eb6d32364637f28be9e9ae9160c6d5c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - ntlm_auth

about:
  home: https://github.com/jborean93/ntlm-auth
  license: LGPL-3.0
  license_file: LICENSE
  summary: 'Calculates NTLM Authentication codes'

  description: |
    This library handles the low-level details of NTLM authentication for use in authenticating 
    with a service that uses NTLM. It will create and parse the 3 different message types in 
    the order required and produce a base64 encoded value that can be attached to the HTTP header.
  dev_url: https://github.com/jborean93/ntlm-auth

extra:
  recipe-maintainers:
    - synapticarbors
