{% set name = "ntlm-auth" %}
{% set version = "1.5.0" %}
{% set sha256 = "c9667d361dc09f6b3750283d503c689070ff7d89f2f6ff0d38088d5436ff8543" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six

test:
  imports:
    - ntlm_auth

about:
  home: https://github.com/jborean93/ntlm-auth
  license: LGPL-3.0
  license_file: LICENSE
  summary: Calculates NTLM Authentication codes

  description: |
    This library handles the low-level details of NTLM authentication for use in authenticating 
    with a service that uses NTLM. It will create and parse the 3 different message types in 
    the order required and produce a base64 encoded value that can be attached to the HTTP header.
  dev_url: https://github.com/jborean93/ntlm-auth

extra:
  recipe-maintainers:
    - synapticarbors
